### PR TITLE
Tailor Profile yoo

### PR DESCRIPTION
**Pull request by LeanKhan**
💯

### CODE REVIEW

**Comment by LeanKhan** [comment]
Did you delete log-in.component.ts?

**Comment by Chibueze-20** [comment]
No I didn't o

**Comment by LeanKhan** [comment]
Oh. No p. What do you think?

**Comment by Chibueze-20** [comment]
I've not merged it with mine yet Sha, I'll pull it today hopefully but it's all good, there shouldn't be any conflict

**Comment by LeanKhan** [comment]
After I used git rm for the package.json files they were deleted :/ 
So I used a git commit HEAD command. After sha I started getting merge conflicts (!) I didn't even push or anything. 
  In the package-lock.json the incoming changes were mostly deletions of package declarations. Like 'Cors' for example. More than 60 of them. 

What do I do abeg? ://

**Comment by LeanKhan** [comment]
I've been accepting some incoming changes though, but most are just deleting packages. So I'm not sure.

**Comment by Chibueze-20** [comment]
I'll have to push then,... don't worry I still have all the needed packages
just keep doing what you are doing, when I push I'll let you know

**Review by Chibueze-20 — APPROVED** [review]
All good

**Comment by Chibueze-20** [comment]
i have pushed mine, the conflicts should be resolved now, i.e just accept incoming changes

**Comment by LeanKhan** [comment]
Aii aii

**Comment by LeanKhan** [comment]
"Redesigned the New Post Component"
What's that?

**Comment by Chibueze-20** [comment]
That's the post component na, where you make a new post

**Pull request merged**
